# Generated by Django 6.0.6 on 2026-06-23 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenamiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parroquia',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parroquia',
            name='ubicacion',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='BarrioCiudadela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero_viviendas', models.IntegerField()),
                ('numero_parques', models.IntegerField()),
                ('numero_edificios_residenciales', models.IntegerField()),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenamiento.parroquia')),
            ],
        ),
        migrations.CreateModel(
            name='PresidenteBarrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('nickname', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('profesion', models.CharField(max_length=100)),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenamiento.barriociudadela')),
            ],
        ),
    ]
